server:
  port: 9190
spring:
  application:
    name: idstaa-service-email
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
      jdbc.time_zone: UTC
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1121245860@qq.com #发送邮件的邮箱地址
    password:  iieildpmrzytifaj #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 587 #端口号465或587
    from: 1121245860@qq.com # 发送邮件的地址，和上面username一致
    debug: true
#注册到Eureka注册中心
eureka:
    client:
        serviceUrl: # eureka server的路径
               ##把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个 eureka server 可以同步注册表
            defaultZone: http://idstaacloudeurekaservera:8761/eureka/,http://idstaacloudeurekaserverb:8762/eureka/
    instance:
    #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
       prefer-ip-address: true
        #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
       instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
       metadata-map:
            # ⾃定义元数据(kv⾃定义)
            cluster: cl1
            region: rn1
