server:
  port: 8081
spring:
  application:
    name: idstaa-service-code
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
      jdbc.time_zone: UTC
#注册到Eureka注册中心
eureka:
    client:
        serviceUrl: # eureka server的路径
               ##把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个 eureka server 可以同步注册表
            defaultZone: http://idstaacloudeurekaservera:8761/eureka/,http://idstaacloudeurekaserverb:8762/eureka/
    instance:
    #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
       prefer-ip-address: true
        #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
       instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
       metadata-map:
            # ⾃定义元数据(kv⾃定义)
            cluster: cl1
            region: rn1
#针对的被调⽤⽅微服务名称,不加就是全局⽣效
idstaa-service-email:
    ribbon:
        #请求连接超时时间
        ConnectTimeout: 2000
        #请求处理超时时间
        ReadTimeout: 10000 #Feign超时时长设置
        #对所有操作都进⾏重试
        OkToRetryOnAllOperations: true
        ####根据如上配置，当访问到故障请求的时候，它会再尝试访问⼀次当前实例（次数由MaxAutoRetries配置），
        ####如果不⾏，就换⼀个实例进⾏访问，如果还不⾏，再换⼀次实例访问（更换次数由MaxAutoRetriesNextServer配置），
        ####如果依然不⾏，返回失败信息。
        MaxAutoRetries: 0 #对当前选中实例重试次数，不包括第⼀次调⽤
        MaxAutoRetriesNextServer: 0 #切换实例的重试次数
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
logging:
    level:
        # Feign⽇志只会对⽇志级别为debug的做出响应
        com.idstaa.feignclient.EmailServiceFeignClient: debug
# 开启feign熔断功能
feign:
    hystrix:
        enabled: false